name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build Rust
        run: cargo build --verbose
      - name: Run Rust tests
        run: cargo test --verbose
      - name: Run Clippy
        run: cargo clippy --all --verbose

  cpp-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install CXX bridge
        run: cargo install cxxbridge-cmd
      - name: Generate CXX headers
        run: |
          mkdir -p target/i686-pc-windows-msvc/cxxbridge/rust/
          cxxbridge --header \
              --output target/i686-pc-windows-msvc/cxxbridge/rust/cxx.h
          mkdir -p target/i686-pc-windows-msvc/cxxbridge/esfpc/src/
          cxxbridge --header src/lib.rs \
              --output target/i686-pc-windows-msvc/cxxbridge/esfpc/src/lib.rs.h
      - name: Install Cppcheck
        run: sudo apt-get install -y cppcheck
      - name: Run Cppcheck
        run: python3 scripts/cppcheck.py
