name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Rust checks
      - name: Build Rust
        run: cargo build --verbose
      - name: Run Rust tests
        run: cargo test --verbose
      # C++ checks
      - name: Install Cppcheck
        run: sudo apt-get install -y cppcheck
      - name: Run Cppcheck
        run: python3 make.py cppcheck
